// Generated by CoffeeScript 1.6.2
(function() {
  var Animal, animals, findAnimal;

  Animal = (function() {
    function Animal(name, sound) {
      this.name = name;
      this.sound = sound;
    }

    return Animal;

  })();

  animals = [new Animal("Dog", "Bark"), new Animal("Cat", "Meow"), new Animal("Mouse", "Squeak"), new Animal("Parrot", "Squark")];

  findAnimal = function(name) {
    var animal, _i, _len, _results;

    _results = [];
    for (_i = 0, _len = animals.length; _i < _len; _i++) {
      animal = animals[_i];
      if (pattern.test(animal)) {
        _results.push(animal);
      }
    }
    return _results;
  };

}).call(this);

/*
//@ sourceMappingURL=.map
*/
